### ISSUE TITLE
Allow fine-tuning of feerate for fundchannel

### ISSUE THREAD

**Issue by dscotese** [Ride-The-Lightning/c-lightning-REST#61]
This is a feature request, that the REST interface accept value for feerate that are composed of digits, possibly followed by "perk" and then a w or a b, as a passthrough to fundchannel as described at https://lightning.readthedocs.io/lightning-fundchannel.7.html.

If feerate is set to something other than `urgent`, `normal`, `slow`, or [digits followed by `perkw` or `perkb`], then it should return an error, "[feerate value submitted] is not a valid value for feerate," and fail the operation.

**Comment by saubyk** [comment]
The openChannel API has support to pass fine tuned fee rate. Instead of passing `urgent`, `normal` or `slow` you can for instance pass `1000perkb` in the `feerate` parameter.

If you're looking for support for the same in the RTL UI, that will be enabled in the next release.
The issue is being tracked below:
https://github.com/Ride-The-Lightning/RTL/issues/676
